// <auto-generated/>
global using Axity.Commons.Filters;
global using Axity.Kafka;
global using [%= company %].[%= name %].Api;[% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Common.DTOs.Requests.[%- controller.name %];[% }); %]
global using [%= company %].[%= name %].Facade;[% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Facade.[%- controller.name %];[% }); %]
global using [%= company %].[%= name %].Persistence;
global using [%= company %].[%= name %].Services;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Serilog.Events;
global using StackExchange.Redis;
global using Steeltoe.Extensions.Configuration.Placeholder;