// <auto-generated/>
global using Axity.ArquetipoUnitTesting.Model.Entities;
global using Axity.ArquetipoUnitTesting.Persistence.Context;
global using Axity.ArquetipoUnitTesting.Persistence.DAO.Tests;
global using Axity.ArquetipoUnitTesting.Persistence.DAO.Tests.Impl;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
