// <auto-generated/>
global using Axity.Commons.Filters;
global using Axity.Kafka;
global using Axity.ArquetipoUnitTesting.Api;
global using Axity.ArquetipoUnitTesting.Common.DTOs.Requests.Tests;
global using Axity.ArquetipoUnitTesting.Facade;
global using Axity.ArquetipoUnitTesting.Facade.Tests;
global using Axity.ArquetipoUnitTesting.Persistence;
global using Axity.ArquetipoUnitTesting.Services;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Serilog.Events;
global using StackExchange.Redis;
global using Steeltoe.Extensions.Configuration.Placeholder;