// <auto-generated/>
global using Axity.ArquetipoUnitTesting.Common.DTOs.Requests.Tests;

global using Axity.ArquetipoUnitTesting.Common.DTOs.Responses.Tests;

global using Axity.ArquetipoUnitTesting.Facade.Tests;
global using Axity.ArquetipoUnitTesting.Facade.Tests.Impl;

global using Axity.ArquetipoUnitTesting.Services.Tests;
global using Microsoft.Extensions.DependencyInjection;