// <auto-generated/>
global using [%= company %].[%= name %].Model.Entities;
global using [%= company %].[%= name %].Persistence.Context;[% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Persistence.DAO.[%- controller.name %];
global using [%= company %].[%= name %].Persistence.DAO.[%- controller.name %].Impl;[% }); %]
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
