// <auto-generated/>
global using AutoMapper;
global using Axity.Commons.Exceptions;
global using Axity.Commons.Extensions;
global using [%= company %].[%= name %].Common;[% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Common.DTOs.Requests.[%- controller.name %];[% }); %][% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Common.DTOs.Responses.[%- controller.name %];[% }); %]
global using [%= company %].[%= name %].Model.Entities;[% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Persistence.DAO.[%- controller.name %];[% }); %]
global using [%= company %].[%= name %].Services.Mapping;[% controllers.forEach(function(controller){ %]
global using [%= company %].[%= name %].Services.[%- controller.name %];
global using [%= company %].[%= name %].Services.[%- controller.name %].Impl;[% }); %]
global using Microsoft.Extensions.DependencyInjection;