// <auto-generated/>
global using AutoMapper;
global using Axity.Commons.Exceptions;
global using Axity.Commons.Extensions;
global using Axity.ArquetipoUnitTesting.Common;
global using Axity.ArquetipoUnitTesting.Common.DTOs.Requests.Tests;
global using Axity.ArquetipoUnitTesting.Common.DTOs.Responses.Tests;
global using Axity.ArquetipoUnitTesting.Model.Entities;
global using Axity.ArquetipoUnitTesting.Persistence.DAO.Tests;
global using Axity.ArquetipoUnitTesting.Services.Mapping;
global using Axity.ArquetipoUnitTesting.Services.Tests;
global using Axity.ArquetipoUnitTesting.Services.Tests.Impl;
global using Microsoft.Extensions.DependencyInjection;