name: NetCore CI
run-name: Construyendo MINTAKA

on:
  push:
    branches:
      - main

jobs:
  ALNILAM:
    uses: JaredDevAxity/AR_26_A_ARCHERNAR_ACTIONS/.github/workflows/MINTAKA_Net.yml@main
    with:   
      node-version: '20'    
      net-version: '3' 
    secrets: inherit     
 
 
